"""Plan-first Jellyfin television organizer."""

from mnamer.organizer.models import (
    PLAN_SCHEMA_VERSION,
    CanonicalShow,
    DuplicateDecision,
    DuplicateDisposition,
    EpisodeMatch,
    ExtraClassification,
    MatchEvidence,
    MatchMethod,
    NumberingMode,
    OrganizerPlan,
    ParsedEpisode,
    PlanItem,
    PlanStatus,
    SourceFingerprint,
    SourceVideo,
    TitlePreference,
)
from mnamer.organizer.overrides import (
    OVERRIDE_SCHEMA_VERSION,
    OverrideCatalog,
    ShowOverride,
    load_show_overrides,
    normalize_show_alias,
)

__all__ = [
    "OVERRIDE_SCHEMA_VERSION",
    "PLAN_SCHEMA_VERSION",
    "CanonicalShow",
    "DuplicateDecision",
    "DuplicateDisposition",
    "EpisodeMatch",
    "ExtraClassification",
    "MatchEvidence",
    "MatchMethod",
    "NumberingMode",
    "OrganizerPlan",
    "OverrideCatalog",
    "ParsedEpisode",
    "PlanItem",
    "PlanStatus",
    "ShowOverride",
    "SourceFingerprint",
    "SourceVideo",
    "TitlePreference",
    "load_show_overrides",
    "normalize_show_alias",
]
